apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wuar-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: wuar.info
      http:   
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
               name: wuar-demo
               port: 
                 number: 8080
