# WildFly Up and Running - Demo
:toc:               left

This demo application showcase of to get https://wildfly.org[WildFly] up and running on the Cloud.

It provides a simple Jakarta EE Web application with a `/reverse` HTTP endpoint that returns the reverse of the `text` input.

It uses MicroProfile Config to configure the default text if no `text` parameter is passed to the HTTP request.

## Prerequisites

To build the application, you need:

* Java 11 or higher installed
* Maven installed
* Docker binary installed

To deploy the application, you need:

* a Kubernetes cluster up and running (for example with https://kind.sigs.k8s.io[Kind]).
* [`kubectl`](https://kubernetes.io/docs/tasks/tools/#kubectl)
* [`helm`](https://helm.sh)

## Build the Application

We use the `image` goal of the `org.wildfly.plugins:wildfly-maven-plugin` to create an application image that contains WildFly and the Web deployment.

You can build the application image with `mvn package`:

[source,bash]
----
$ mvn clean package
...
[INFO] Successfully built application image ghcr.io/wildfly-up-and-running/wuar-demo:latest
----

At the end of the Maven execution, the application image has been built with the name `ghcr.io/wildfly-up-and-running/wuar-demo`.

## Run the Application Locally With Docker

You can run the application image with:

[source,bash]
----
$ docker run -p 8080:8080 ghcr.io/wildfly-up-and-running/wuar-demo
...
11:06:15,546 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 27.0.0.Beta1 (WildFly Core 19.0.0.Beta18) started in 2755ms - Started 261 of 358 services (145 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
----

Once the application is started, we can query it with:

[source,bash]
----
$ curl "http://localhost:8080/reverse?text=Bonjour"
ruojnoB
----

## Run Integration Tests Against The Application

The application is tested using https://www.testcontainers.org[Testcontainers]. This allows to write integration tests with JUnit that are testing the actual application (composed of WildFly and the Web deployment inside the image).

[source,bash]
----
mvn clean verify
----

## Deploy the Application on Kubernetes

To deploy a fully functional applicaton on Kubernetes (with healthiness probes, resource requiremetns etc.) we can use the https://github.com/wildfly/wildfly-charts/blob/main/charts/wildfly/README.md[Helm Chart for WildFly] with the configuration specific to the demo in a `helm.yaml` file.

[source,bash]
----
helm install wuar-demo wildfly \
  -f https://raw.githubusercontent.com/wildfly-up-and-running/wuar-demo/main/helm.yaml \
  --repo https://docs.wildfly.org/wildfly-charts/
----

We can watch the application being deployed with:

[source,bash]
----
$ kubectl get deployment wuar-demo -w
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
wuar-demo   0/1     1            0           14s
wuar-demo   1/1     1            1           55s
----

The application is now up and running on Kubernetes.

It is not exposed oustide of the Kubernetes cluster so we will use Port Forwarding to access it from the outside by running:

[source,bash]
----
kubectl port-forward deployment/wuar-demo 8080:8080
----

We can now use the application on the `localhost:8080` URL:

[source,bash]
----
$ curl "http://localhost:8080/reverse"
!setenrebuK morf olleH
$ curl "http://localhost:8080/reverse?text=No+lemon,+No+Melon"
noleM oN ,nomel oN
----
